import { I18nManager } from 'react-native';

import {
  ACCESSORY_SIZE,
  fontScale,
  INPUT_FONT_SIZE,
  LINE_HEIGHT_DELTA,
  TEXT_FIELD_ACCESSORY_MARGIN_HORIZONTAL,
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL,
  BASELINE_TEXT_FIELD_PADDING_VERTICAL,
  BASELINE_TEXT_FIELD_HEIGHT,
} from '../constants';

// ==================
// LAYOUT SUPPORT
// ==================

const isRTL = I18nManager.getConstants().isRTL;
const layoutSupportMultiplier = isRTL ? -1 : 1;

// ==================
// LABEL POSITIONING
// ==================
export const LABEL_PADDING_HORIZONTAL = 4;

export const LABEL_START_OFFSET_WITH_ACCESSORY =
  ACCESSORY_SIZE +
  TEXT_FIELD_ACCESSORY_MARGIN_HORIZONTAL +
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL -
  LABEL_PADDING_HORIZONTAL;

export const ACTIVE_LABEL_TOP_POSITION =
  (-BASELINE_TEXT_FIELD_PADDING_VERTICAL + LINE_HEIGHT_DELTA) * fontScale;

export const LABEL_TRANSLATE_X_WITH_ACCESSORY =
  -layoutSupportMultiplier *
  (ACCESSORY_SIZE +
    TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL -
    LABEL_PADDING_HORIZONTAL);

export const LABEL_TRANSLATE_X_WITHOUT_ACCESSORY =
  -layoutSupportMultiplier * LABEL_PADDING_HORIZONTAL;

// ============
// OPACITY
// ============

export const DISABLED_OUTLINE_OPACITY = 0.12;

// ==================
// MULTILINE POSITIONING
// ==================

export const MULTILINE_PADDING_TOP =
  ((BASELINE_TEXT_FIELD_HEIGHT -
    2 * BASELINE_TEXT_FIELD_PADDING_VERTICAL -
    INPUT_FONT_SIZE) /
    2 -
    LINE_HEIGHT_DELTA) *
  fontScale;
